baseURL = "https://d-dorazio.github.io"
languageCode = "en-us"

# this title is used only for rss readers which do not agree upon whether to
# interpret them as html text or not.
title = "dapo"

enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "friendly"

# chroma is still too immature
pygmentsUseClassic = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
    name = "Daniele D'Orazio"
