baseURL = "https://d-dorazio.github.io"
languageCode = "en-us"

# this title is used only for rss readers which do not agree upon whether to
# interpret them as html text or not.
title = "dapo"

enableEmoji = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
  [markup.highlight]
    style = "friendly"

[author]
    name = "Daniele D'Orazio"
