baseURL = "https://d-dorazio.github.io"
languageCode = "en-us"

# escape & in d&#39; because otherwise feed readers see an "'"
title = "d&amp;#39;"

enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "friendly"

# chroma is still too immature
pygmentsUseClassic = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
    name = "Daniele D'Orazio"
