baseURL = "https://d-dorazio.github.io"
languageCode = "en-us"
title = "d&#39;"

enableEmoji = true

pygmentsCodeFences = true
pygmentsStyle = "friendly"

# chroma is still too immature
pygmentsUseClassic = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
    name = "Daniele D'Orazio"
